services:

  fastapi:
    build: ./fastapi
    container_name: fastapi
    env_file:
      - .env
    ports:
      - "8000:80"
    volumes:
      - ./fastapi:/app
    depends_on:
      postgresql:
        condition: service_healthy

  react:
    build: ./react
    container_name: react
    env_file:
      - .env
    ports:
      - "5173:5173"
    volumes:
      - ./react:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  postgresql:
    image: postgres:16-alpine
    container_name: postgresql
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql/init.sql:/docker-entrypoint-initdb.d/sqlinit.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
